version: '3.1'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: eta
      MYSQL_DATABASE: eta
      MYSQL_USER: eta
      MYSQL_PASSWORD: eta